/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["readiness"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/responses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createResponse"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/chat/completions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createChatCompletion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/threads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listSessionThreads"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listJobs"];
    put?: never;
    post: operations["createJob"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getJob"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs/{id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getJobEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs/{id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["cancelJob"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs/{id}/approvals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["decideJobApproval"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/batches": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createBatch"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/routes/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["previewRoute"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/models": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Discover Codex reasoning efforts and exact ChatGPT web thinking-depth labels before creating a job. The web model's auto ID is not a depth. */
    get: operations["listModels"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/models/{modelId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["updateModel"];
    trace?: never;
  };
  "/api/v1/quota": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getQuota"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chatgpt-web/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getChatGptWebStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chatgpt-web/accounts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listChatGptWebAccounts"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chatgpt-web/accounts/{accountId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["updateChatGptWebAccount"];
    trace?: never;
  };
  "/api/v1/chatgpt-web/routing-weights": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["updateChatGptWebRoutingWeights"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chatgpt-web/qualification-runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listChatGptWebQualificationRuns"];
    put?: never;
    post: operations["createChatGptWebQualificationRun"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chatgpt-web/qualification-runs/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getChatGptWebQualificationRun"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/usage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getUsage"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/audit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listAuditEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/retention/receipts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listDeletionReceipts"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/bootstrap/keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["bootstrapApiKey"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listApiKeys"];
    put?: never;
    post: operations["createApiKey"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/keys/{id}/revoke": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["revokeApiKey"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/passkey/register/options": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["beginPasskeyRegistration"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/passkey/register/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["verifyPasskeyRegistration"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/passkey/login/options": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["beginPasskeyLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/passkey/login/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["verifyPasskeyLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/recovery/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["loginWithRecoveryCode"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Health: {
      status: string;
      service: string;
    };
    CreateApiKeyRequest: {
      name: string;
      scopes: (
        | "admin"
        | "jobs:read"
        | "jobs:write"
        | "quota:read"
        | "keys:write"
        | "approvals:write"
        | "chatgpt:web"
      )[];
      /** @description Explicit execution channels allowed for this key; omitted requests preserve the legacy scope-derived behavior */
      executionChannels?: ("codex" | "chatgpt_web")[];
      /** @default 60 */
      rateLimitPerMinute: number;
      /**
       * Format: date-time
       * @description Omit for the 30-day default; null requests a non-expiring administrator key
       */
      expiresAt?: string | null;
      executionPolicy?: components["schemas"]["ExecutionPolicy"];
    };
    RevokeApiKeyRequest: {
      confirmationPrefix: string;
    };
    ApiKeyMetadata: {
      /** Format: uuid */
      id: string;
      name: string;
      prefix: string;
      scopes: string[];
      /** @description Execution channels enforced by the API for this key */
      executionChannels: ("codex" | "chatgpt_web")[];
      executionPolicy: components["schemas"]["ExecutionPolicy"];
      rateLimitPerMinute: number;
      /** Format: date-time */
      expiresAt?: string | null;
      /** Format: date-time */
      revokedAt?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      lastUsedAt?: string | null;
    };
    CreatedApiKey: components["schemas"]["ApiKeyMetadata"] & {
      /** @description Plaintext API key returned only once */
      key: string;
      /** @description True when the same idempotent request is replayed */
      replayed?: boolean;
    };
    AuditEvent: {
      /** Format: uuid */
      id: string;
      actorId: string;
      action: string;
      resourceType: string;
      resourceId: string | null;
      metadata: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      createdAt: string;
    };
    DeletionReceipt: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      jobId: string;
      /** Format: date-time */
      payloadDeletedAt: string;
      /** Format: date-time */
      metadataDeleteAfter: string;
    };
    /** @enum {string} */
    PermissionPreset: "restricted" | "confirm" | "full";
    AialraExtension: {
      permission_preset?: components["schemas"]["PermissionPreset"];
      session_key?: string;
      /** @enum {string} */
      session_mode?: "ephemeral" | "persistent";
      deadline_ms?: number;
      /** @enum {string} */
      execution_channel?: "codex" | "chatgpt_web";
      /** @enum {string} */
      chatgpt_mode?: "chat" | "search" | "deep_research";
      /** @description Exact label from GET /api/v1/models webThinkingDepths. For ChatGPT web this is the only supported explicit depth parameter; omission uses the page default. Standard reasoning_effort is rejected for web jobs. */
      thinking_depth?: string;
      /**
       * @default temporary_per_request
       * @enum {string}
       */
      conversation_mode: "temporary_per_request" | "persistent_per_request";
      /**
       * @description Chat and search use Temporary Chat; Deep Research requires false.
       * @default true
       */
      temporary_chat: boolean;
      /**
       * @description Must be true for Deep Research because the new ordinary conversation remains in ChatGPT history and may use account personalization.
       * @default false
       */
      deep_research_persistence_acknowledged: boolean;
      require_sources?: boolean;
    };
    ExecutionPolicy: {
      defaultPreset: components["schemas"]["PermissionPreset"];
      allowedPresets: components["schemas"]["PermissionPreset"][];
    };
    PermissionProfile: {
      preset?: components["schemas"]["PermissionPreset"];
      /**
       * @default read
       * @enum {string}
       */
      filesystem: "none" | "read" | "write";
      /**
       * @default none
       * @enum {string}
       */
      network: "none" | "allowlist" | "all";
      allowedHosts?: string[];
      /** @default true */
      requireApprovalForWrites: boolean;
      /** @default true */
      requireApprovalForExternalActions: boolean;
    };
    TaskContract: {
      objective: string;
      /**
       * @default general
       * @enum {string}
       */
      taskKind: "bounded" | "coding" | "review" | "planning" | "batch" | "general";
      requiredContext?: string[];
      constraints?: string[];
      expectedOutput?: string;
      validation?: {
        responseSchema?: {
          [key: string]: unknown;
        };
        checks?: (
          | {
              /** @constant */
              type: "equals";
              expected: string;
              /** @default true */
              trim: boolean;
            }
          | {
              /** @constant */
              type: "contains";
              expected: string;
            }
        )[];
        acceptanceTests?: string[];
      };
      /**
       * @default internal
       * @enum {string}
       */
      dataClassification: "public" | "internal" | "confidential" | "restricted";
      permissions?: components["schemas"]["PermissionProfile"];
      /** @default 120000 */
      deadlineMs: number;
      budget?: {
        maxCodexCredits?: number;
        /** @default 8192 */
        maxOutputTokens: number;
        /** @default 2 */
        maxAttempts: number;
      };
      sessionKey?: string;
      /**
       * @default ephemeral
       * @enum {string}
       */
      sessionMode: "ephemeral" | "persistent";
      /**
       * @default codex
       * @enum {string}
       */
      executionChannel: "codex" | "chatgpt_web";
      chatgptWeb?: {
        /** @enum {string} */
        mode: "chat" | "search" | "deep_research";
        /**
         * @default temporary_per_request
         * @enum {string}
         */
        conversationMode: "temporary_per_request" | "persistent_per_request";
        /** @default true */
        temporaryChat: boolean;
        /** @default false */
        personalized: boolean;
        /**
         * @description Explicit acknowledgement required for persistent Deep Research calls.
         * @default false
         */
        persistenceAcknowledged: boolean;
        requireSources: boolean;
        /** @description Exact webThinkingDepths label, verified before submission. */
        thinkingDepth?: string;
      };
      /** @default auto */
      model: string;
      /**
       * @description Codex reasoning effort. For ChatGPT web jobs use chatgptWeb.thinkingDepth instead; this legacy field does not select a web depth.
       * @default medium
       * @enum {string}
       */
      effort: "minimal" | "low" | "medium" | "high" | "xhigh" | "max";
      /** @default true */
      replayable: boolean;
      ambiguity?: number;
      risk?: number;
    };
    CreateJobRequest: {
      task: components["schemas"]["TaskContract"];
      metadata?: {
        [key: string]: string;
      };
    };
    Job: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      status:
        | "accepted"
        | "awaiting_approval"
        | "queued"
        | "running"
        | "validating"
        | "succeeded"
        | "failed"
        | "cancelled"
        | "expired";
      task: components["schemas"]["TaskContract"];
      route?: components["schemas"]["RouteDecision"] | null;
      webExecution?: components["schemas"]["WebExecutionSummary"];
      output?: unknown;
      usage: components["schemas"]["UsageLedger"];
      validation?: unknown;
      errorCode?: string | null;
      errorMessage?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** Format: date-time */
      expiresAt: string;
    };
    /** @description Available on GET /api/v1/jobs/{id} for web jobs; derived from the job's sanitized events, never from a guessed model tier. */
    WebExecutionSummary: {
      accountId: string | null;
      requestedThinkingDepth: string | null;
      resolvedThinkingDepth: string | null;
      thinkingDepthVerified: boolean;
    };
    JobEvent: {
      id: string;
      /** Format: uuid */
      jobId: string;
      sequence: number;
      /** @enum {string} */
      type: "status" | "output.delta" | "tool" | "approval" | "validation" | "usage" | "error";
      data: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      createdAt: string;
    };
    RouteDecision: {
      /** @enum {string} */
      provider: "codex" | "chatgpt_web";
      model: string;
      /** @description Codex routing effort. For a ChatGPT web route this retained value does not represent the effective page thinking depth; read webExecution instead. */
      effort: string;
      policyVersion: string;
      reasonCode: string;
      /** @constant */
      sticky: true;
    };
    UsageLedger: {
      inputTokens: number;
      cachedInputTokens: number;
      outputTokens: number;
      /** @description Codex subscription credits calculated from the official credit rate card */
      codexCredits: number | null;
      /** @description Estimated token-only cost at official API rates; not an actual subscription charge */
      apiEquivalentUsd: number | null;
      /** @description Observed quota-window usage before the task */
      quotaUsedPercentBefore: number | null;
      /** @description Observed quota-window usage after the task */
      quotaUsedPercentAfter: number | null;
      /** @description Observed percentage-point change when both snapshots belong to the same quota window */
      quotaWindowDeltaPercent: number | null;
      allocatedSubscriptionUsd: number | null;
      /** @enum {string} */
      measurementStatus?: "measured" | "unavailable";
      /** @enum {string} */
      subscriptionChannel?: "codex" | "chatgpt_pro_web";
      sourceCount?: number | null;
      durationMs?: number | null;
      attemptCount?: number;
      retryCount?: number;
    };
    QuotaSnapshot: {
      /** @constant */
      provider: "codex";
      usedPercent: number | null;
      windowDurationMinutes: number | null;
      /** Format: date-time */
      resetsAt: string | null;
      planType: string | null;
      /** Format: date-time */
      fetchedAt: string;
      /** @enum {string} */
      source: "app-server" | "unavailable";
      stale: boolean;
      windows: components["schemas"]["QuotaWindow"][];
    };
    QuotaWindow: {
      id: string;
      name: string;
      /** @enum {string} */
      kind: "primary" | "secondary";
      usedPercent: number | null;
      remainingPercent: number | null;
      windowDurationMinutes: number | null;
      /** Format: date-time */
      resetsAt: string | null;
    };
    RuntimeModel: {
      id: string;
      displayName: string;
      /** @enum {string} */
      provider: "codex" | "chatgpt_web";
      available: boolean;
      enabled: boolean;
      hidden: boolean;
      isDefault: boolean;
      supportedReasoningEfforts: string[];
      /** @description Exact labels observed on the current web UI across eligible accounts; do not infer a model or a subscription tier from them. */
      webThinkingDepths?: string[];
      defaultWebThinkingDepth?: string | null;
      defaultReasoningEffort: string | null;
      inputModalities: string[];
      creditRate: {
        [key: string]: unknown;
      } | null;
      apiRate: {
        [key: string]: unknown;
      } | null;
      /** @enum {string} */
      rateStatus: "available" | "unavailable";
      /** @enum {string} */
      streamingMode: "delta" | "final_only";
      /** Format: date-time */
      discoveredAt: string;
    };
    ChatGptWebStatus: {
      configuredEnabled: boolean;
      diagnosticEnabled: boolean;
      effectiveConcurrency: number;
      maximumConcurrency: number;
      activeTabs: number;
      queuedJobs: number;
      sandboxVerified: boolean;
      extensionConnected: boolean;
      pageReady: boolean;
      authenticated: boolean;
      /** @enum {string} */
      circuitState: "closed" | "cooldown" | "open" | "qualification_required";
      circuitReason: string | null;
      /** Format: date-time */
      cooldownUntil: string | null;
      /** @enum {string} */
      rateLimitState: "clear" | "cooldown" | "recovery_probe" | "observation";
      retryAfter: number | null;
      /** Format: date-time */
      lastRateLimitAt: string | null;
      consecutiveRateLimits: number;
      /** @enum {string} */
      conversationMode: "temporary_per_request" | "persistent_per_request";
      temporaryChatVerified: boolean;
      /** Format: date-time */
      lastRecoveryProbeAt: string | null;
      lastRecoveryProbePassed: boolean | null;
      /** Format: date-time */
      lastSubmissionAt: string | null;
      successesAtCurrentLevel: number;
      attemptsAtCurrentLevel: number;
      severeErrorsAtCurrentLevel: number;
      /** Format: date-time */
      lastQualifiedAt: string | null;
      lastQualificationPassed: boolean | null;
      lastQualificationSucceeded: number | null;
      adapterVersion: string;
      /** @enum {string} */
      phase:
        | "idle"
        | "preparing"
        | "input_verified"
        | "submitted"
        | "generating"
        | "completed"
        | "failed"
        | "resetting";
      /** Format: uuid */
      activeJobId: string | null;
      activeAttempt: number | null;
      /** Format: date-time */
      lastHeartbeatAt: string | null;
      lastFailureCode: string | null;
      /** Format: date-time */
      lastResetAt: string | null;
      quarantinedTabs: number;
      slots: {
        /** Format: uuid */
        slotId: string;
        /** @enum {string} */
        state:
          | "starting"
          | "idle"
          | "preparing"
          | "ready"
          | "submitted"
          | "generating"
          | "completed"
          | "quarantined";
        submitted: boolean;
        /** Format: date-time */
        quarantinedUntil: string | null;
        /** Format: date-time */
        updatedAt: string;
      }[];
      /** Format: uuid */
      lastQualificationRunId: string | null;
      accounts: components["schemas"]["ChatGptWebAccount"][];
      /** Format: date-time */
      updatedAt: string;
    };
    ChatGptWebAccount: {
      accountId: string;
      /** @enum {string} */
      slot: "a" | "b" | "c" | "d";
      label: string;
      /** @enum {string} */
      plan: "plus" | "pro" | "unknown";
      /** @default 0 */
      routingWeight: number;
      quota: components["schemas"]["ChatGptWebAccountQuota"];
      enabled: boolean;
      qualified: boolean;
      /** @enum {string} */
      state:
        | "configured"
        | "login_required"
        | "ready"
        | "busy"
        | "cooldown"
        | "quarantined"
        | "disabled"
        | "stale";
      /** @constant */
      maxConcurrency: 1;
      extensionConnected: boolean;
      pageReady: boolean;
      authenticated: boolean;
      sandboxVerified: boolean;
      /** Format: uuid */
      activeJobId: string | null;
      /** Format: date-time */
      leaseExpiresAt: string | null;
      /** @default 0 */
      leaseEpoch: number;
      /** @default 0 */
      stateVersion: number;
      /** @enum {string} */
      rateLimitState: "clear" | "cooldown" | "recovery_probe" | "observation";
      retryAfter: number | null;
      consecutiveRateLimits: number;
      /** Format: date-time */
      lastRateLimitAt: string | null;
      /** Format: date-time */
      lastSubmissionAt: string | null;
      /** Format: date-time */
      lastHeartbeatAt: string | null;
      /** Format: date-time */
      lastProbeAt: string | null;
      lastProbePassed: boolean | null;
      /** Format: date-time */
      lastSuccessAt: string | null;
      /** Format: date-time */
      lastFailureAt: string | null;
      lastFailureCode: string | null;
      failurePhase: string | null;
      diagnosticSummary: Record<string, never> | null;
      vncPath: string;
      /** Format: date-time */
      updatedAt: string;
    };
    ChatGptWebAccountQuota: {
      /** @enum {string} */
      status: "fresh" | "stale" | "unavailable";
      /** @constant */
      source: "chatgpt-usage";
      /** Format: date-time */
      fetchedAt: string | null;
      windows: {
        /** @enum {string} */
        kind: "primary" | "secondary";
        usedPercent: number | null;
        remainingPercent: number | null;
        windowDurationMinutes: number | null;
        /** Format: date-time */
        resetsAt: string | null;
      }[];
      errorCode: string | null;
    };
    ChatGptWebQualificationItem: {
      index: number;
      name: string;
      /** @enum {string} */
      mode: "chat" | "search" | "deep_research";
      /** @enum {string} */
      status: "pending" | "running" | "succeeded" | "failed";
      durationMs: number | null;
      outputLength: number | null;
      outputSha256: string | null;
      sourceCount: number | null;
      errorCode: string | null;
      submittedCount: number;
      /** @default 0 */
      recoveryCount: number;
      ownershipMatched: boolean | null;
      /** @enum {string} */
      conversationMode: "temporary_per_request" | "persistent_per_request";
      /** @default false */
      temporaryChatVerified: boolean;
      /** @default false */
      persistentChatVerified: boolean;
      /** @enum {string|null} */
      failurePhase?:
        | "opening"
        | "configuring"
        | "temporary_chat_verified"
        | "persistent_chat_verified"
        | "mode_selected"
        | "input_ready"
        | "command_accepted"
        | "action_started"
        | "submitted"
        | "user_echo_verified"
        | "generating"
        | "stabilizing"
        | "resetting"
        | "reset_completed"
        | null;
      diagnosticSummary?: {
        /** @enum {string} */
        pageKind: "home" | "conversation" | "other";
        userTurnCount: number;
        assistantTurnCount: number;
        latestUserMatchesObjective: boolean | null;
        generationActive: boolean;
        latestAssistantHasText: boolean;
        visibleErrorKinds: ("continue_generating" | "retry" | "generation_error" | "other")[];
        temporaryChatVerified: boolean;
        resolvedThinkingDepth: string | null;
      } | null;
    };
    ChatGptWebQualificationRun: {
      /** Format: uuid */
      id: string;
      accountId: string | null;
      /** @enum {string} */
      suite: "readiness" | "single_probe" | "chat_3" | "chat_10" | "deep_2" | "full_10";
      /** @enum {string} */
      status: "accepted" | "running" | "succeeded" | "failed" | "cancelled";
      total: number;
      completed: number;
      succeeded: number;
      failed: number;
      items: components["schemas"]["ChatGptWebQualificationItem"][];
      errorCode: string | null;
      createdBy: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      startedAt: string | null;
      /** Format: date-time */
      completedAt: string | null;
      /** Format: date-time */
      updatedAt: string;
    };
    SessionThread: {
      sessionKey: string;
      callerId: string;
      model: string;
      /** @enum {string} */
      effort: "minimal" | "low" | "medium" | "high" | "xhigh" | "max";
      turnCount: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      lastUsedAt: string;
      /** Format: date-time */
      expiresAt: string;
    };
    ChatCompletionsRequest: {
      /** @default auto */
      model: string;
      messages: {
        /** @enum {string} */
        role: "system" | "developer" | "user" | "assistant";
        content: string;
        name?: string;
      }[];
      /** @default false */
      stream: boolean;
      stream_options?: {
        /** @default false */
        include_usage: boolean;
      };
      max_tokens?: number;
      max_completion_tokens?: number;
      response_format?:
        | {
            /** @constant */
            type?: "text";
          }
        | {
            /** @constant */
            type?: "json_object";
          }
        | {
            /** @constant */
            type: "json_schema";
            json_schema: {
              name?: string;
              schema?: {
                [key: string]: unknown;
              };
              strict?: boolean;
            };
          };
      /**
       * @description Codex only; rejected with HTTP 400 for ChatGPT web requests. Use aialra.thinking_depth for web.
       * @enum {string}
       */
      reasoning_effort?: "minimal" | "low" | "medium" | "high" | "xhigh" | "max";
      metadata?: {
        [key: string]: string;
      };
      aialra?: components["schemas"]["AialraExtension"];
    };
    ChatCompletion: {
      id: string;
      /** @constant */
      object: "chat.completion";
      created: number;
      model: string;
      choices: {
        /** @constant */
        index: 0;
        message: {
          /** @constant */
          role: "assistant";
          content: string;
        };
        /** @enum {string} */
        finish_reason: "stop" | "length";
      }[];
      usage?: {
        prompt_tokens: number;
        completion_tokens: number;
        total_tokens: number;
      };
      aialra?: {
        job_id?: string;
        session_key?: string | null;
        /** @enum {string} */
        measurement_status?: "measured" | "unavailable";
        /** @enum {string|null} */
        conversation_mode?: "temporary_per_request" | "persistent_per_request" | null;
        /** @enum {string} */
        data_retention?: "persistent_chat_history" | "temporary_or_provider_managed";
      };
    };
    ResponsesRequest: {
      /** @default auto */
      model: string;
      input: string | unknown[];
      instructions?: string;
      /** @description Codex only; reasoning.effort is rejected for ChatGPT web requests. Use aialra.thinking_depth for web. */
      reasoning?: {
        /** @enum {string} */
        effort?: "minimal" | "low" | "medium" | "high" | "xhigh" | "max";
      };
      text?: {
        format?: {
          /** @enum {string} */
          type?: "text" | "json_schema";
          name?: string;
          schema?: Record<string, never>;
          strict?: boolean;
        };
      };
      /** @default false */
      stream: boolean;
      metadata?: {
        [key: string]: string;
      };
      max_output_tokens?: number;
      aialra?: components["schemas"]["AialraExtension"];
    };
    Response: {
      id: string;
      /** @constant */
      object: "response";
      status: string;
      model: string;
      output?: unknown;
      error?: unknown;
      usage: components["schemas"]["UsageLedger"];
      metadata: Record<string, never>;
    };
    ErrorEnvelope: {
      error: {
        code: string;
        message: string;
        retryAfter?: number;
        details?: unknown;
      };
    };
  };
  responses: {
    /** @description Unsupported parameter or invalid request */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description Idempotency key reused with a different request digest */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description ChatGPT web input exceeds the safe browser limit (`chatgpt_web_input_too_long`); no task is created */
    WebInputTooLong: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description ChatGPT web cooldown or recovery probe is active (`chatgpt_rate_limited`) */
    TooManyRequests: {
      headers: {
        /** @description Seconds before the caller should try a new request */
        "Retry-After": number;
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description Resource not found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
    /** @description Authentication failed or bootstrap is unavailable */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorEnvelope"];
      };
    };
  };
  parameters: {
    IdempotencyKey: string;
    IdempotencyKeyOptional: string;
    JobId: string;
    BootstrapToken: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Process is alive */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  readiness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service dependencies are ready */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  createResponse: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResponsesRequest"];
      };
    };
    responses: {
      /** @description Completed response or Server-Sent Events stream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Response"];
          "text/event-stream": string;
        };
      };
      400: components["responses"]["BadRequest"];
      409: components["responses"]["Conflict"];
      422: components["responses"]["WebInputTooLong"];
      429: components["responses"]["TooManyRequests"];
    };
  };
  createChatCompletion: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: components["parameters"]["IdempotencyKeyOptional"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatCompletionsRequest"];
      };
    };
    responses: {
      /** @description Completed chat completion or Server-Sent Events stream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatCompletion"];
          "text/event-stream": string;
        };
      };
      400: components["responses"]["BadRequest"];
      409: components["responses"]["Conflict"];
      422: components["responses"]["WebInputTooLong"];
      429: components["responses"]["TooManyRequests"];
      /** @description The underlying call failed */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description The call is still running; poll the native Jobs API */
      504: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  listSessionThreads: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Resumable conversation threads visible to the caller */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["SessionThread"][];
          };
        };
      };
    };
  };
  listJobs: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Recent jobs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["Job"][];
          };
        };
      };
    };
  };
  createJob: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateJobRequest"];
      };
    };
    responses: {
      /** @description Job accepted, queued, or waiting for execution approval */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Job"];
        };
      };
      409: components["responses"]["Conflict"];
      422: components["responses"]["WebInputTooLong"];
      429: components["responses"]["TooManyRequests"];
    };
  };
  getJob: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["JobId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current job snapshot */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Job"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  getJobEvents: {
    parameters: {
      query?: {
        after?: number;
        stream?: boolean;
      };
      header?: never;
      path: {
        id: components["parameters"]["JobId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Event collection or Server-Sent Events stream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["JobEvent"][];
          };
          "text/event-stream": string;
        };
      };
    };
  };
  cancelJob: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        id: components["parameters"]["JobId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cancellation requested or terminal job returned */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Job"];
        };
      };
    };
  };
  decideJobApproval: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        id: components["parameters"]["JobId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @enum {string} */
          decision: "approved" | "denied";
          reason?: string;
        };
      };
    };
    responses: {
      /** @description Approval decision recorded and current job returned */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Job"];
        };
      };
    };
  };
  createBatch: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          requests: components["schemas"]["CreateJobRequest"][];
        };
      };
    };
    responses: {
      /** @description Jobs accepted */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["Job"][];
          };
        };
      };
      429: components["responses"]["TooManyRequests"];
    };
  };
  previewRoute: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          task: components["schemas"]["TaskContract"];
        };
      };
    };
    responses: {
      /** @description Deterministic route decision */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RouteDecision"];
        };
      };
    };
  };
  listModels: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Runtime Codex model catalog merged with Router settings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["RuntimeModel"][];
          };
        };
      };
    };
  };
  updateModel: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        modelId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          enabled: boolean;
        };
      };
    };
    responses: {
      /** @description Model setting updated or replayed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getQuota: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Latest worker-published quota snapshot */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuotaSnapshot"];
        };
      };
    };
  };
  getChatGptWebStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Secret-free health, circuit and qualification state for the experimental web channel */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatGptWebStatus"];
        };
      };
    };
  };
  listChatGptWebAccounts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Secret-free state for the fixed ChatGPT web account slots */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["ChatGptWebAccount"][];
          };
        };
      };
    };
  };
  updateChatGptWebAccount: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        accountId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          label?: string;
          /** @enum {string} */
          plan?: "plus" | "pro" | "unknown";
          enabled?: boolean;
        };
      };
    };
    responses: {
      /** @description Updated secret-free account state */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatGptWebAccount"];
        };
      };
    };
  };
  updateChatGptWebRoutingWeights: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          weights: {
            accountId: string;
            weight: number;
          }[];
        };
      };
    };
    responses: {
      /** @description Atomically updated account routing weights whose total is 100 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["ChatGptWebAccount"][];
          };
        };
      };
    };
  };
  listChatGptWebQualificationRuns: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Recent secret-free qualification runs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["ChatGptWebQualificationRun"][];
          };
        };
      };
    };
  };
  createChatGptWebQualificationRun: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @enum {string} */
          suite: "readiness" | "single_probe" | "chat_3" | "chat_10" | "deep_2" | "full_10";
          accountId?: string;
        };
      };
    };
    responses: {
      /** @description Qualification run accepted or replayed */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatGptWebQualificationRun"];
        };
      };
    };
  };
  getChatGptWebQualificationRun: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description One secret-free qualification run */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatGptWebQualificationRun"];
        };
      };
    };
  };
  getUsage: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Codex Credits, API-equivalent estimates, and accepted-result totals */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            accepted_tasks: number;
            codex_credits: number;
            /** @description Estimated token-only cost at official API rates */
            api_equivalent_usd: number;
            credits_per_accepted_task: number | null;
            api_equivalent_usd_per_accepted_task: number | null;
            allocated_subscription_usd: number;
          };
        };
      };
    };
  };
  listAuditEvents: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Administrative audit events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["AuditEvent"][];
          };
        };
      };
    };
  };
  listDeletionReceipts: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Payload deletion receipts and metadata deletion deadlines */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["DeletionReceipt"][];
          };
        };
      };
    };
  };
  bootstrapApiKey: {
    parameters: {
      query?: never;
      header: {
        "X-Bootstrap-Token": components["parameters"]["BootstrapToken"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description First administrator API key, shown once */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreatedApiKey"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  listApiKeys: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API key metadata without key digests */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            data: components["schemas"]["ApiKeyMetadata"][];
          };
        };
      };
    };
  };
  createApiKey: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateApiKeyRequest"];
      };
    };
    responses: {
      /** @description API key metadata and one-time plaintext key */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreatedApiKey"];
        };
      };
    };
  };
  revokeApiKey: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RevokeApiKeyRequest"];
      };
    };
    responses: {
      /** @description API key revoked */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** Format: uuid */
            id: string;
            revoked: boolean;
            alreadyRevoked: boolean;
          };
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  beginPasskeyRegistration: {
    parameters: {
      query?: never;
      header: {
        "X-Bootstrap-Token": components["parameters"]["BootstrapToken"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
          displayName?: string;
        };
      };
    };
    responses: {
      /** @description WebAuthn registration challenge and browser options */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  verifyPasskeyRegistration: {
    parameters: {
      query?: never;
      header: {
        "X-Bootstrap-Token": components["parameters"]["BootstrapToken"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: uuid */
          challengeId: string;
          response: Record<string, never>;
        };
      };
    };
    responses: {
      /** @description Registration result and ten one-time recovery codes */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  beginPasskeyLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
        };
      };
    };
    responses: {
      /** @description WebAuthn authentication challenge and browser options */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  verifyPasskeyLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: uuid */
          challengeId: string;
          response: Record<string, never>;
        };
      };
    };
    responses: {
      /** @description Authentication result with an HttpOnly session cookie */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  loginWithRecoveryCode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: email */
          email: string;
          code: string;
        };
      };
    };
    responses: {
      /** @description Authentication result after consuming one recovery code */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current application session revoked and cookie cleared */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            loggedOut: boolean;
          };
        };
      };
    };
  };
}
